### ISSUE TITLE
PenziteleTodoist

### ISSUE THREAD

**Issue by JamesVanWaza** [JamesVanWaza/penzitele#1]
# ToDO

- [ ] Setup SSH - https://cloud.google.com/compute/docs/instances/connecting-advanced#thirdpartytools
- [ ] Find phpmyadmin login and export db 
- [ ] Redesign Login Page on Adobe XD and import it to WP 
- [ ] Add Algolia Search Plugin 
- [ ] Update permalink urls
